---
kind: pipeline
name: android

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: syncloud/android-sdk
  environment:
    KEY_STORE:
      from_secret: KEY_STORE
    ANDROID_STORE_FILE:
      from_secret: ANDROID_STORE_FILE
    ANDROID_STORE_PASSWORD:
      from_secret:  ANDROID_STORE_PASSWORD
    ANDROID_KEY_ALIAS:
      from_secret: ANDROID_KEY_ALIAS
    ANDROID_KEY_PASSWORD:
      from_secret: ANDROID_KEY_PASSWORD
    commands:
      - ./gradlew clean test assemble

- name: artifact
  image: appleboy/drone-scp
  settings:                                         command_timeout: 2m
    host:                                             from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud/build/outputs/apk/prod/release/*
    strip_components: 1                             target: /home/artifact/repo/redirect/${DRONE_BUILD_NUMBER}
    timeout: 2m                                     username: artifact
  when:
    status:
    - failure
    - success

...
