---
kind: pipeline
name: android

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: syncloud/android-sdk
  commands:
    - yes | /opt/android/tools/bin/sdkmanager "build-tools;30.0.2"
    - ./gradlew clean test assembleDebug

- name: apk
  image: syncloud/android-sdk
  environment:
    KEY_STORE:
      from_secret: KEY_STORE
    ANDROID_STORE_FILE:
      from_secret: ANDROID_STORE_FILE
    ANDROID_STORE_PASSWORD:
      from_secret:  ANDROID_STORE_PASSWORD
    ANDROID_KEY_ALIAS:
      from_secret: ANDROID_KEY_ALIAS
    ANDROID_KEY_PASSWORD:
      from_secret: ANDROID_KEY_PASSWORD
  commands:
    - yes | /opt/android/tools/bin/sdkmanager "build-tools;30.0.2"
    - ./gradlew clean test assemble
  when:
    branch:
    - stable

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
        from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud/build/outputs/apk/prod/release/*
    strip_components: 6
    target: /home/artifact/repo/android/${DRONE_BUILD_NUMBER}
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

...
